# Generated by Django 4.1.7 on 2023-02-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_events_race_alter_events_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='name',
        ),
    ]
