# Generated by Django 4.1.7 on 2023-02-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_events_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('RACE', 'Race'), ('QUAL', 'Qualifying'), ('P1', 'Practice 1'), ('P2', 'Practice 2'), ('P3', 'Practice 3'), ('SPRT', 'Sprint')], max_length=4),
        ),
    ]
